use serde_json::Value;
use std::collections::BTreeSet;
use std::path::Path;

const QUICK_READ_COMMANDS: &[&str] = &[
    "get_environment_snapshot",
    "get_environment_revision",
    "get_favorites",
];

#[test]
fn application_command_acl_sources_match_invoke_handler_exactly() {
    let handler_commands = invoke_handler_commands(include_str!("../src/lib.rs"))
        .expect("lib.rs must contain a parseable generate_handler! command list");
    let build_script = include_str!("../build.rs");

    assert!(
        build_script.contains("AppManifest"),
        "build.rs must register a Tauri AppManifest so custom commands participate in ACL checks"
    );
    assert!(
        build_script.contains(".app_manifest("),
        "the AppManifest must be attached to tauri_build::Attributes"
    );
    assert!(
        build_script.contains(".commands(COMMANDS)"),
        "the AppManifest must generate permissions for application commands"
    );
    let manifest_commands = build_manifest_commands(build_script)
        .expect("build.rs must contain a parseable COMMANDS list");
    let main_commands =
        capability_application_commands(include_str!("../capabilities/default.json"));
    let generated_commands = generated_permission_commands(Path::new(env!("CARGO_MANIFEST_DIR")))
        .expect("generated application permissions must be parseable");

    assert_same_commands("build.rs COMMANDS", &handler_commands, &manifest_commands)
        .expect("build manifest command drift");
    assert_same_commands("main capability", &handler_commands, &main_commands)
        .expect("main capability command drift");
    assert_same_commands(
        "permissions/autogenerated",
        &handler_commands,
        &generated_commands,
    )
    .expect("generated permission command drift");
}

#[test]
fn quick_window_capability_exposes_only_read_only_application_commands() {
    let permissions = capability_permissions(include_str!("../capabilities/quick.json"));
    let expected = QUICK_READ_COMMANDS
        .iter()
        .map(|command| (*command).to_owned())
        .collect::<BTreeSet<_>>();

    assert_eq!(
        capability_application_commands(include_str!("../capabilities/quick.json")),
        expected,
        "quick must not receive any mutating application command permission"
    );
    assert!(permissions.contains("clipboard-manager:allow-write-text"));
}

#[test]
fn toggle_favorite_holds_the_environment_service_guard_through_settings_update() {
    let api_source = include_str!("../src/api.rs");
    let function = source_between(
        api_source,
        "pub fn toggle_favorite(",
        "pub fn analyze_path_entries(",
    );
    let guard_line = function
        .lines()
        .find(|line| line.contains("= lock_service(&state)?;"))
        .expect(
            "toggle_favorite must bind the EnvironmentService MutexGuard before checking existence",
        );
    let guard_name = guard_line
        .trim()
        .strip_prefix("let ")
        .and_then(|line| line.split_once('='))
        .map(|(name, _)| name.trim())
        .expect("the service guard must be a named local binding");
    let snapshot_use = format!("{guard_name}.snapshot()");

    assert!(
        function.contains(&snapshot_use),
        "the existence snapshot must be read through the named service guard"
    );
    assert!(
        function.find(guard_line.trim()).unwrap() < function.find(".settings").unwrap(),
        "the service guard must be acquired before the settings write"
    );
    assert!(
        !function.contains(&format!("drop({guard_name})")),
        "the service guard must remain in scope until settings.toggle completes"
    );
}

#[test]
fn exact_command_contract_rejects_synthetic_missing_and_stale_sources() {
    let handler = command_set(&["read_environment", "write_environment"]);
    let missing = command_set(&["read_environment"]);
    let stale = command_set(&[
        "read_environment",
        "write_environment",
        "removed_environment_command",
    ]);

    let missing_error = assert_same_commands("synthetic missing source", &handler, &missing)
        .expect_err("a missing command must fail the contract");
    assert!(missing_error.contains("write_environment"));

    let stale_error = assert_same_commands("synthetic stale source", &handler, &stale)
        .expect_err("a stale command must fail the contract");
    assert!(stale_error.contains("removed_environment_command"));
}

fn capability_permissions(source: &str) -> BTreeSet<String> {
    serde_json::from_str::<Value>(source)
        .expect("capability must be valid JSON")
        .get("permissions")
        .and_then(Value::as_array)
        .expect("capability permissions must be an array")
        .iter()
        .map(|permission| {
            permission
                .as_str()
                .expect("capability permission must be a string")
                .to_owned()
        })
        .collect()
}

fn capability_application_commands(source: &str) -> BTreeSet<String> {
    capability_permissions(source)
        .into_iter()
        .filter_map(|permission| {
            permission
                .strip_prefix("allow-")
                .map(|command| command.replace('-', "_"))
        })
        .collect()
}

fn invoke_handler_commands(source: &str) -> Result<BTreeSet<String>, String> {
    let body = source
        .split_once("tauri::generate_handler![")
        .and_then(|(_, remainder)| remainder.split_once("]);").map(|(body, _)| body))
        .ok_or_else(|| "generate_handler! list not found".to_owned())?;

    body.split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| {
            entry
                .strip_prefix("api::")
                .map(str::to_owned)
                .ok_or_else(|| format!("unexpected generate_handler! entry: {entry}"))
        })
        .collect()
}

fn build_manifest_commands(source: &str) -> Result<BTreeSet<String>, String> {
    let body = source
        .split_once("const COMMANDS: &[&str] = &[")
        .and_then(|(_, remainder)| remainder.split_once("];").map(|(body, _)| body))
        .ok_or_else(|| "build COMMANDS list not found".to_owned())?;

    body.split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| {
            entry
                .strip_prefix('"')
                .and_then(|entry| entry.strip_suffix('"'))
                .map(str::to_owned)
                .ok_or_else(|| format!("unexpected build COMMANDS entry: {entry}"))
        })
        .collect()
}

fn generated_permission_commands(manifest_dir: &Path) -> Result<BTreeSet<String>, String> {
    let directory = manifest_dir.join("permissions/autogenerated");
    let entries = std::fs::read_dir(&directory)
        .map_err(|error| format!("failed to read {}: {error}", directory.display()))?;
    let mut commands = BTreeSet::new();

    for entry in entries {
        let path = entry
            .map_err(|error| format!("failed to read permission entry: {error}"))?
            .path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
            continue;
        }
        let command = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .ok_or_else(|| format!("permission filename is not UTF-8: {}", path.display()))?;
        let source = std::fs::read_to_string(&path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        validate_generated_permission(&source, command)
            .map_err(|error| format!("{}: {error}", path.display()))?;
        commands.insert(command.to_owned());
    }

    Ok(commands)
}

fn validate_generated_permission(source: &str, command: &str) -> Result<(), String> {
    let document =
        toml::from_str::<toml::Value>(source).map_err(|error| format!("invalid TOML: {error}"))?;
    let permissions = document
        .get("permission")
        .and_then(toml::Value::as_array)
        .ok_or_else(|| "permission array is missing".to_owned())?;
    let identifier = command_permission(command);
    let allow_entries = permissions
        .iter()
        .filter(|permission| {
            permission.get("identifier").and_then(toml::Value::as_str) == Some(identifier.as_str())
        })
        .collect::<Vec<_>>();
    if allow_entries.len() != 1 {
        return Err(format!(
            "expected exactly one {identifier} definition, found {}",
            allow_entries.len()
        ));
    }
    let allowed_commands = allow_entries[0]
        .get("commands")
        .and_then(|commands| commands.get("allow"))
        .and_then(toml::Value::as_array)
        .ok_or_else(|| format!("{identifier} commands.allow is missing"))?
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::to_owned)
                .ok_or_else(|| format!("{identifier} commands.allow must contain strings"))
        })
        .collect::<Result<BTreeSet<_>, _>>()?;
    let expected = command_set(&[command]);
    assert_same_commands(&identifier, &expected, &allowed_commands)
}

fn assert_same_commands(
    source: &str,
    expected: &BTreeSet<String>,
    actual: &BTreeSet<String>,
) -> Result<(), String> {
    if expected == actual {
        return Ok(());
    }
    let missing = expected.difference(actual).cloned().collect::<Vec<_>>();
    let stale = actual.difference(expected).cloned().collect::<Vec<_>>();
    Err(format!(
        "{source} differs from invoke_handler; missing={missing:?}, stale={stale:?}"
    ))
}

fn command_set(commands: &[&str]) -> BTreeSet<String> {
    commands
        .iter()
        .map(|command| (*command).to_owned())
        .collect()
}

fn command_permission(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

fn source_between<'a>(source: &'a str, start: &str, end: &str) -> &'a str {
    source
        .split_once(start)
        .map(|(_, remainder)| remainder)
        .and_then(|remainder| remainder.split_once(end).map(|(body, _)| body))
        .expect("expected function markers in source")
}
